export const images = [
    {
        category: 'food',
        images: [
            'cheese',
            'cake',
            'cherry',
            'coconut',
            'hamburger',
            'meat',
            'sandwich',
            'watermelon',
        ],
        rus: [
            'сыр',
            'пирог',
            'вишня',
            'кокос',
            'гамбургер',
            'мясо',
            'бутерброд',
            'арбуз',
        ],
    },
    {
        category: 'clothes',
        images: [
            'blouse',
            'bag',
            'dress',
            'hat',
            'skirt',
            'sweater',
            't-shirt',
            'trousers',
        ],
        rus: [
            'блуза',
            'сумка',
            'платье',
            'шляпа',
            'юбка',
            'свитер',
            'футболка',
            'штаны',
        ],
    },
    {
        category: 'emotions',
        images: [
            'angry',
            'bored',
            'happy',
            'insidious',
            'sad',
            'scared',
            'shy',
            'surprised',
        ],
        rus: [
            'злой',
            'скучающий',
            'счастливый',
            'коварный',
            'грустный',
            'испуганный',
            'стеснительный',
            'удивленный',
        ],
    },
    {
        category: 'animals-a',
        images: [
            'eagle',
            'giraffe',
            'lamb',
            'octopus',
            'owl',
            'shark',
            'snake',
            'squirrel',
        ],
        rus: [
            'орел',
            'жираф',
            'ягненок',
            'осминог',
            'сова',
            'акула',
            'змея',
            'белка',
        ],
    },
    {
        category: 'animals-b',
        images: [
            'cat',
            'crab',
            'dog',
            'fish',
            'fox',
            'panda',
            'raccoon',
            'zebra',
        ],
        rus: [
            'кот',
            'краб',
            'собака',
            'рыба',
            'лиса',
            'панда',
            'енот',
            'зебра',
        ],
    },
    {
        category: 'actions-a',
        images: [
            'dance',
            'fly',
            'read',
            'ring',
            'run',
            'sing',
            'ski',
            'swim',
        ],
        rus: [
            'танцевать',
            'летать',
            'читать',
            'звонить',
            'бежать',
            'петь',
            'кататься на лыжах',
            'плавать',
        ],
    },
    {
        category: 'actions-b',
        images: [
            'catch',
            'cry',
            'hang',
            'jump',
            'present',
            'sleep',
            'walk',
            'teach',
        ],
        rus: [
            'ловить',
            'плакать',
            'висеть',
            'прыгать',
            'дарить',
            'спать',
            'ходить',
            'обучать',
        ],
    },
    {
        category: 'actions-c',
        images: [
            'carry',
            'cook',
            'drink',
            'eat',
            'giggle',
            'hug',
            'ride',
            'scratch',
        ],
        rus: [
            'нести',
            'готовить',
            'пить',
            'есть',
            'хихикать',
            'обнимать',
            'ехать',
            'царапать',
        ],
    },
];
